First working version of a new shell module
orellazri/roll pull request #3
Opened 2023-07-28 12:59 UTC by aviadhaham

2023-07-28 13:45 UTC, orellazri commented
Looks really good! I think we should not separate the argument though, maybe the only parameter for now should be a full command, and you can pass it to `utils.RunCommand` with "bash" as the first command, and "-c" as the first argument and then the full command as the last argument

2023-07-28 13:47 UTC, orellazri requested changes
Looks really good! I think we should not separate the argument though, maybe the only parameter for now should be a full command, and you can pass it to utils.RunCommand with "bash" as the first command, and "-c" as the first argument and then the full command as the last argument

2023-07-28 13:47 UTC, orellazri commented on internal/modules/shell/shell.go
> +	}
This is not needed since Command doesn't have an "optional" tag, so it will fail when parsing the blueprint anyways.

2023-07-28 13:47 UTC, orellazri commented on cmd/root.go
> +	Short: "An extremely fast and scalable configuration management tool.",
This can be a separate PR, but you can keep it if you're having trouble separating the commits and rebasing,

2023-07-28 14:47 UTC, aviadhaham commented on cmd/root.go
> +	Short: "An extremely fast and scalable configuration management tool.",
yeah didn't mean to actually, it slipped accidentally
I just rebased and forced push all good

2023-07-28 15:38 UTC, orellazri commented on internal/modules/shell/shell.go
> +	}
So how I would approach it is try to isolate it. I would create an empty go file (new project, etc.) or just modify this project's main.go, and try to run something like this:

```go
cmd := exec.Command("bash", "-c", "echo -e 'test\ntest1' > /tmp/text.txt")
out, err := cmd.CombinedOutput()
if err != nil {
	log.Fatal(err)
}
fmt.Println(string(out))
```

In your case, I see you are splitting `m.Command` by spaces and then adding it to args, but since the whole command is running inside the `bash -c` context, this is not needed, so you can ask the user for the full command (which might be very complicated and not only separated by spaces), and pass it as the only argument, like I did in the example above.
Sounds good? 😄

2023-07-28 21:08 UTC, aviadhaham commented on internal/modules/shell/shell.go
> +	}
not in front of pc now

as for the splitting, it was because i noticed the RunCommand function expects two arguments, and the latter is a slice of strings. Could I have avoided that ?

As for the debugging and isolation, yeah i’ll try thanks man
tha thing is, it’s harder for me to think of options as I still not fully understand the flow of execution i think

@orellazri

2023-07-29 05:58 UTC, orellazri commented on internal/modules/shell/shell.go
> +	}
Yeah that's absolutely understandable.

As for the splitting, I meant that you split the actual command like so: `args := strings.Split(m.Command, " ")`
It's true that `utils.RunCommand` expects a command and an arguments slice, so it's fine that you created a slice with "-c" and appended to it, but you might want to append the actual full command without separating it, like so:

```
func (m *ShellModule) Run() error {
	return utils.RunCommand("bash", []string{"-c", m.Command})
}
```
(Did not test this, but you can try to play around and see if it works for you)

2023-07-30 06:37 UTC, aviadhaham commented on internal/modules/shell/shell.go
> +	}
@orellazri working now, nice, wonder what was the difference. On first look it seems only different in terms of structure, not functionality. But, nevermind.
New commit with the new implementation: https://github.com/orellazri/roll/pull/3/commits/e821973b0adf43e1a99907bb9a78c7f3061f3e55

2023-07-30 06:53 UTC, orellazri requested changes
Looks good! Just fix the notes I made and we can merge it 😄

2023-07-30 06:53 UTC, orellazri commented on internal/modules/shell/shell.go
> +	return utils.RunCommand(cmd, []string{"-c", m.Command})
I think for now you can hardcode "bash" instead of having it in a variable
The next feature you can work on would be making this also come as a parameter 😉

2023-07-30 06:53 UTC, orellazri commented on examples/linux.hcl
> +// }
Could you uncomment this as it's not related to this PR?

2023-07-30 06:53 UTC, orellazri commented on examples/linux.hcl
> +//     name = "ranger"
Same, uncomment

2023-07-30 06:53 UTC, orellazri commented on examples/linux.hcl
> +    // command = "echo -e 'test\ntest1' > /tmp/text.txt && cat /tmp/text.txt | grep 1 >> /tmp/another_file.txt"
Delete the comment

2023-07-30 07:03 UTC, aviadhaham commented
All required changes are done, you may merge on your time @orellazri :)

2023-07-30 07:25 UTC, orellazri commented
> All required changes are done, you may merge on your time @orellazri :)

@aviadhaham Thanks! I just need you to fix the conflict since I can't merge with it. I renamed linux.hcl to blueprint.hcl so just move your new task there and that's it

2023-07-31 20:07 UTC, aviadhaham commented
> > All required changes are done, you may merge on your time @orellazri :)
> 
> @aviadhaham Thanks! I just need you to fix the conflict since I can't merge with it. I renamed linux.hcl to blueprint.hcl so just move your new task there and that's it

Check now please 👍

2023-08-01 06:59 UTC, orellazri approved these changes

2023-08-01 06:59 UTC, merged